// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLD9QLFqH-5HS0mRfolbWpkD6LwfyQLr8',
    appId: '1:410882510246:web:b892f4750aa9fcfbdc9367',
    messagingSenderId: '410882510246',
    projectId: 'mis-lab3-37348',
    authDomain: 'mis-lab3-37348.firebaseapp.com',
    storageBucket: 'mis-lab3-37348.firebasestorage.app',
    measurementId: 'G-V4YYHB6Q99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASVudAJKQiXfg2_DxzZGofo-RRHZIH3DQ',
    appId: '1:410882510246:android:2d0d96f414bef3a3dc9367',
    messagingSenderId: '410882510246',
    projectId: 'mis-lab3-37348',
    storageBucket: 'mis-lab3-37348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0HWWxp4zfmPqIFrdi79C5XI7D-Bl9J8',
    appId: '1:410882510246:ios:d7650cfa6b7f3474dc9367',
    messagingSenderId: '410882510246',
    projectId: 'mis-lab3-37348',
    storageBucket: 'mis-lab3-37348.firebasestorage.app',
    iosBundleId: 'com.example.laboratoryExercise2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLD9QLFqH-5HS0mRfolbWpkD6LwfyQLr8',
    appId: '1:410882510246:web:d9cc7c2e5e74ceb5dc9367',
    messagingSenderId: '410882510246',
    projectId: 'mis-lab3-37348',
    authDomain: 'mis-lab3-37348.firebaseapp.com',
    storageBucket: 'mis-lab3-37348.firebasestorage.app',
    measurementId: 'G-6VJWSBW86K',
  );

}